name: hello_dapp_flutter
description: A new Flutter project.

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  web3dart: ^3.0.0
  http: ^1.6.0
  web_socket_channel: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - src/artifacts/HelloWorld.json
